#ifndef __UART_CONFIG_H__
#define __UART_CONFIG_H__

#define UART_MAX_BUFFER_SIZE    100

#define UART_9600_BAUD_RATE 9600
#define UART_9600_BAUD_RATE_UBRRL_VALUE 103

#define UART_115200_BAUD_RATE 115200
#define UART_115200_BAUD_RATE_UBRRL_VALUE 8

#define UART_SEND_BUFFER_EMPTY 1
#define UART_DATA_RECEVIED 1

#define UART_ASYNC_MDOE 1
#define UART_SYNC_MDOE 2
//----------
#define UART_MODE  UART_ASYNC_MDOE


#define UART_WITH_ODD_PARITY_MODE 1
#define UART_WITH_EVEN_PARITY_MODE 2
#define UART_WITOUT_PARITY_MODE 3
//--------------
#define UART_PARITY_MODE  UART_WITH_PARITY_MODE


#define UART_ONE_STOP_MODE 1
#define UART_WITH_TWO_STOP_MODE 2
//---------------
#define UART_STOP_BITS_MODE  UART_ONE_STOP_MODE

#define UART_DELEMITER '*'
#define UART_END_OF_STRING '\0'
#endif // __UART_CONFIG_H__
