#ifndef _ICU_CONFIG_H_
#define _ICU_CONFIG_H_

#include "DIO_interface.h"

#define ICU_PORT_INDEX DIO_PORTB
#define ICU_PIN_INDEX DIO_PIN3

#define ICU_TIMER1_MAX 65536UL
#define ICU_1_MILLION_MICRO_TIME_STAMP 1000000UL

#define ICU_RISING_EDGE_MODE 1
#define ICU_FALLING_EDGE_MODE 2

#define ICU_CONT_MODE_SELECTED 1
#define ICU_ONE_SHOT_MODE_SELECTED 2

#define ICU_SELECTED_EDGE   ICU_RISING_EDGE_MODE
#define ICU_CONTINIOUS_MODE   ICU_ONE_SHOT_MODE_SELECTED




#endif //_ICU_CONFIG_H_