#ifndef __I2C_CONFIG_H__
#define __I2C_CONFIG_H__

#define I2C_MASTER_SELECTED 1
#define I2C_SLAVE_SELECTED 2
#define I2C_MODE I2C_MASTER_SELECTED

#define GET_CURRENT_STATE() (TWSR & 0xF8)

#define I2C_START_CONDITION_TRANSMITTED 0x08
#define I2C_REPEATED_START_CONDITION_TRANSMITTED 0x10

#endif // __I2C_CONFIG_H__
